version: '3.8'

services:
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "9001:8081"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

#  task-service:
#    build: ./task-service
#    container_name: task-service
#    ports:
#      - "9002:8082"
#    depends_on:
#      - mysql
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_db?useSSL=false&allowPublicKeyRetrieval=true
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: task_db
    ports:
      - "3306:3306"
    volumes:
      - C:/Users/RAHUL KUNAMALLA/Desktop/mysqlcontainerdata

#  rabbitmq:
#    image: rabbitmq:3-management
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"  # RabbitMQ message broker
#      - "15672:15672" # RabbitMQ management UI

volumes:
  mysql_data:
