
services:
  mysql-user:
    image: mysql:latest
    container_name: mysql_user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user_db
      MYSQL_USER: rahul
      MYSQL_PASSWORD: Rahul@123
    ports:
      - "3307:3306"  # Separate port for user-service
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql-task:
    image: mysql:latest
    container_name: mysql_task
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
      MYSQL_USER: rahul
      MYSQL_PASSWORD: Rahul@123
    ports:
      - "3308:3306"  # Separate port for task-service
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  mysql-submission:
    image: mysql:latest
    container_name: mysql_submission
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: submission_db
      MYSQL_USER: rahul
      MYSQL_PASSWORD: Rahul@123
    ports:
      - "3309:3306"  # Separate port for task-service
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 3

  user-service:
    build:
      context: ./user-service
    image: user-service:latest
    container_name: user_service_container
    depends_on:
      mysql-user:
        condition: service_healthy
    environment:
      SERVER_PORT: 9001
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user:3306/user_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: rahul
      SPRING_DATASOURCE_PASSWORD: Rahul@123
    ports:
      - "9001:9001"

  task-service:
    build:
      context: ./task-service
    image: task-service:latest
    container_name: task_service_container
    depends_on:
      mysql-task:
        condition: service_healthy
      user-service:
        condition: service_started
    environment:
      SERVER_PORT: 9002
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-task:3306/task_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: rahul
      SPRING_DATASOURCE_PASSWORD: Rahul@123
      USER_SERVICE_URL: http://user-service:9001
    ports:
      - "9002:9002"

  submission-service:
    build:
      context: ./submission-service
    image: submission-service:latest
    container_name: submission_service_container
    depends_on:
      mysql-submission:
        condition: service_healthy
      user-service:
        condition: service_started
      task-service:
        condition: service_started
    environment:
      SERVER_PORT: 9003
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-submission:3306/submission_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: rahul
      SPRING_DATASOURCE_PASSWORD: Rahul@123
      USER_SERVICE_URL: http://user-service:9001
      TASK_SERVICE_URL: http://task-service:9002
    ports:
      - "9003:9003"
