services:
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_db
      MYSQL_USER: rahul
      MYSQL_PASSWORD: Rahul@123
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  user-service:
    build:
      context: .
    image: user-service:latest
    container_name: user_service_container
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker  # Fixed syntax here
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/task_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: rahul
      SPRING_DATASOURCE_PASSWORD: Rahul@123
    ports:
      - "9001:9001"
